import type { Metadata } from "next";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Digital Artisans",
    default: "Digital Artisans", 
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
